import {
 collection,
 addDoc,
} from "firebase/firestore";
import { db } from "../../lib/firebase";

export const seedMenu = async () => {
 const items = [
   /* =========================
      HOT COFFEE
   ========================== */
   {
     name: "Americano",
     category: "Hot Coffee",
     price: 190,
     description: "Espresso + hot water, pure and raw",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Cappuccino",
     category: "Hot Coffee",
     price: 239,
     description: "Espresso + less foam, stronger than latte",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Latte",
     category: "Hot Coffee",
     price: 219,
     description: "Espresso + more milk, smooth & balanced",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Mocha",
     category: "Hot Coffee",
     price: 259,
     description: "Espresso + homemade chocolate + milk",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Vietnamese Coffee",
     category: "Hot Coffee",
     price: 219,
     description: "Espresso + condensed milk, bold & sweet",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      COLD COFFEE
   ========================== */
   {
     name: "Cola Iced Espresso",
     category: "Cold Coffee",
     price: 249,
     description: "Espresso with cola, refreshing & energizing",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Cold Coffee",
     category: "Cold Coffee",
     price: 219,
     description: "Blended coffee, milk, sweet & rich",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Cranberry Iced Espresso",
     category: "Cold Coffee",
     price: 219,
     description: "Espresso with cranberry, juicy & intense",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Ginger Ale Espresso",
     category: "Cold Coffee",
     price: 249,
     description: "Espresso with ginger ale, zesty & refreshing",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Iced Americano",
     category: "Cold Coffee",
     price: 190,
     description: "Espresso + ice + cold water, pure & bold",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Iced Mocha",
     category: "Cold Coffee",
     price: 259,
     description: "Chilled mocha, chocolate + milk + ice",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Iced Vietnamese",
     category: "Cold Coffee",
     price: 219,
     description: "Espresso + condensed milk + ice",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Redbull Iced Espresso",
     category: "Cold Coffee",
     price: 349,
     description: "Espresso with Redbull, intense energy boost",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      COFFEE ADD-ONS
   ========================== */
   {
     name: "Almond Milk",
     category: "Coffee Add-Ons",
     price: 40,
     description: "Almond milk substitute add-on",
     isAddon: true,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Hazelnut",
     category: "Coffee Add-Ons",
     price: 30,
     description: "Hazelnut flavor add-on",
     isAddon: true,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Oat Milk",
     category: "Coffee Add-Ons",
     price: 40,
     description: "Oat milk substitute add-on",
     isAddon: true,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Vanilla",
     category: "Coffee Add-Ons",
     price: 40,
     description: "Vanilla flavor add-on",
     isAddon: true,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      NON COFFEE & REFRESHERS
   ========================== */
   {
     name: "Butter Milk",
     category: "Non-Coffee & Refreshers",
     price: 79,
     description: "Refreshing salted & mildly spiced",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Classic Iced Coke",
     category: "Non-Coffee & Refreshers",
     price: 79,
     description: "Coke + ice, fizzy & refreshing",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Diet Iced Coke",
     category: "Non-Coffee & Refreshers",
     price: 79,
     description: "Zero calorie fizzy refreshment",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Hot Chocolate",
     category: "Non-Coffee & Refreshers",
     price: 249,
     description: "Velvety chocolate + milk, balanced",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Lemon Cola",
     category: "Non-Coffee & Refreshers",
     price: 99,
     description: "Fresh lemon squeeze on Coke",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Lemonade",
     category: "Non-Coffee & Refreshers",
     price: 79,
     description: "Fresh lemonade, sweet & tangy",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Redbull Chilled",
     category: "Non-Coffee & Refreshers",
     price: 170,
     description: "Chilled Redbull + ice",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      SNACKS & BITES
   ========================== */
   {
     name: "Chicken Nuggets Peri-Peri",
     category: "Snacks & Bites",
     price: 199,
     description: "Signature peri-peri nuggets",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Chicken Nuggets Salted",
     category: "Snacks & Bites",
     price: 169,
     description: "Salted crispy nuggets",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Falafel Salted",
     category: "Snacks & Bites",
     price: 169,
     description: "Salted falafel",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "French Fries Peri-Peri",
     category: "Snacks & Bites",
     price: 179,
     description: "Peri-peri seasoned fries",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "French Fries Salted",
     category: "Snacks & Bites",
     price: 149,
     description: "Salted crispy fries",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Garlic Chilli Pops Peri-Peri",
     category: "Snacks & Bites",
     price: 189,
     description: "Garlic chilli pops with twist",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Garlic Chilli Pops Salted",
     category: "Snacks & Bites",
     price: 159,
     description: "Crispy garlic chilli pops",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      DESSERTS
   ========================== */
   {
     name: "Choco Chunk Brownie",
     category: "Desserts",
     price: 119,
     description: "Brownie with choco chunks",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Choco Lava",
     category: "Desserts",
     price: 119,
     description: "Molten chocolate lava cake",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      HOT TEA
   ========================== */
   {
     name: "Butterfly Pea Flower Tea",
     category: "Hot Tea",
     price: 199,
     description: "Soothing herbal infusion",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Chamomile Tea",
     category: "Hot Tea",
     price: 199,
     description: "Calming chamomile tea",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   {
     name: "Hibiscus Tea",
     category: "Hot Tea",
     price: 199,
     description: "Tangy hibiscus infusion",
     isAddon: false,
     isService: false,
     serviceUnit: null,
     isActive: true,
   },
   /* =========================
      SERVICES
   ========================== */
   {
     name: "Workspace Booking",
     category: "Workspace",
     price: 249,
     description: "Workspace access per day (redeemable)",
     isAddon: false,
     isService: true,
     serviceUnit: "day",
     isActive: true,
   },
   {
     name: "Snooker - Small Table",
     category: "Snooker",
     price: 299,
     description: "Small table booking per hour",
     isAddon: false,
     isService: true,
     serviceUnit: "hour",
     isActive: true,
   },
   {
     name: "Snooker - English Table",
     category: "Snooker",
     price: 399,
     description: "English table booking per hour",
     isAddon: false,
     isService: true,
     serviceUnit: "hour",
     isActive: true,
   },
   {
     name: "Foosball Booking",
     category: "Games",
     price: 299,
     description: "Foosball per hour",
     isAddon: false,
     isService: true,
     serviceUnit: "hour",
     isActive: true,
   },
   {
     name: "Motion Games",
     category: "Games",
     price: 299,
     description: "Motion games per hour",
     isAddon: false,
     isService: true,
     serviceUnit: "hour",
     isActive: true,
   },
 ];
 for (let item of items) {
   await addDoc(collection(db, "menuItems"), item);
 }
 alert("Menu seeded successfully!");
};